services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/deno-devcontainer-boilerplate:cached
